name: notes
description: Notes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  sqflite: ^2.0.2
  dartz: ^0.10.1
  flutter_modular: ^4.4.0
  animations: ^2.0.2
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  unicons: ^2.0.2
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  shimmer: ^2.0.0

flutter:
  uses-material-design: true

dev_dependencies: 
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2
