name: notes
description: Notes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  sqflite: ^2.0.2
  dartz: ^0.10.1

flutter:
  uses-material-design: true