name: notes
description: Notes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  fpdart: ^0.0.12
  sqflite: ^2.0.2

flutter:
  uses-material-design: true